@startsalt devtools
{
{T
 + DevTools
 ++ Android
 +++ build-tools    
 +++ emulator  
 +++ licenses   
 +++ platform-tools  
 +++ system-images
 +++ cmdline-tools  
 +++ extras    
 +++ platforms  
 +++ skins
}
}
@endsalt
